### ISSUE TITLE
Deploy problem

### ISSUE THREAD

**Issue by jc-su** [mateusasferreira/nft-marketplace#1]
When I deploy it to Mumbai test net. I got some error messages like that

  reason: 'too many arguments:  in Contract constructor',
  code: 'UNEXPECTED_ARGUMENT',
  count: 1,
  expectedCount: 0

But the contract was created, I can see it on plygon Mumbai scan. So I just ignore it.

After enter to localhost website and 'create asset' I got the error like that

![微信截图_20211223130553](https://user-images.githubusercontent.com/17023515/147238319-d3c0a3c8-160d-4d71-9a53-ad4f4d56bd95.png)

**Comment by mateusasferreira** [comment]
This is new to me but I think it is probably related to the deploy scripts, try it like this again: 
```
//the string argument must match your marketplace smart contract name
const NFTMarket = await hre.ethers.getContractFactory("NFTMarket");
  const nftMarket = await NFTMarket.deploy();
  await nftMarket.deployed();
 
  const NFT = await hre.ethers.getContractFactory("NFT");
  const nft = await NFT.deploy(nftMarket.address);
  await nft.deployed();

```

**Comment by jc-su** [comment]
Thanks for your reply. the first problem was solved. But there are still some problems on web page. Please see the screenshot
![微信截图_20211223130553](https://user-images.githubusercontent.com/17023515/147289327-f2ebaaa0-44b7-45df-9134-9112dfb3d965.png)
![微信截图_20211223213409](https://user-images.githubusercontent.com/17023515/147289380-3b2dd5a1-2192-4a69-820b-72d2474a37dd.png)

**Comment by jc-su** [comment]
> Thanks for your reply. the first problem was solved. But there are still some problems on web page. Please see the screenshot ![微信截图_20211223130553](https://user-images.githubusercontent.com/17023515/147289327-f2ebaaa0-44b7-45df-9134-9112dfb3d965.png) ![微信截图_20211223213409](https://user-images.githubusercontent.com/17023515/147289380-3b2dd5a1-2192-4a69-820b-72d2474a37dd.png)

Can you upload those page?
